title:            Sebastian Poskitt-Marshall
description:      A Coding Story

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: 

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Projects'
    url: '/projects'
    submenu:
      - title: 'Advanced Procedural Methods'
        url: '/AdvancedProceduralMethods/'
      - title: 'Dungeons & Janitors'
        url: '/Dungeons-Janitors/'
      - title: 'Programming for Games'
        url: '/ProgrammingForGames/'
      - title: 'SmartTome'
        url: "#"
  - title: 'Blog'
    url: '/posts'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'

# Owner/author information
owner:
  name:           Sebastian Poskitt-Marshall
  site:           
  avatar:         images/avatar.jpg
  bio:            "Often found on fire. Occasionally codes video games and can play Touhou on Lunatic. Time is an illusion. Lunch time doubly so."
  email:          sposkittmarshall@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: FruitPunchCoder # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: KappaRepublic

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/KappaRepublic"
  - title: "linkedin"

# Background image to be tiled on all pages
background:   images/logo.png

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    GMT
locale:      en_UK
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 12

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
